services:
  backend:
    build: 
      context: ./backend
      dockerfile: API/Dockerfile
    ports:
      - "5272:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: